table dim_plan
	lineageTag: 0442cb4d-5d1b-4202-92d9-2ac40b8fc22b

	column plan_key
		dataType: int64
		formatString: 0
		lineageTag: e785322c-dfd7-4d25-b2f8-9fa1501a796d
		summarizeBy: none
		sourceColumn: plan_key

		annotation SummarizationSetBy = Automatic

	column international_plan
		dataType: string
		lineageTag: f4df98c2-e6c6-46db-97f2-b00df6ab699b
		summarizeBy: none
		sourceColumn: international_plan

		annotation SummarizationSetBy = Automatic

	column voice_mail_plan
		dataType: string
		lineageTag: 980cbb55-b601-442a-8ecc-ddc7e27181b4
		summarizeBy: none
		sourceColumn: voice_mail_plan

		annotation SummarizationSetBy = Automatic

	partition dim_plan = m
		mode: import
		queryGroup: teleco_churn_model
		source =
				let
				    Source = complete_data,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"state", "account_length", "area_code", "number_vmail_messages", "total_day_minutes", "total_day_calls", "total_day_charge", "total_eve_minutes", "total_eve_calls", "total_eve_charge", "total_night_minutes", "total_night_calls", "total_night_charge", "total_intl_minutes", "total_intl_calls", "total_intl_charge", "customer_service_calls", "churn", "customer_key"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Uppercased Text" = Table.TransformColumns(#"Added Index",{{"international_plan", Text.Upper, type text}, {"voice_mail_plan", Text.Upper, type text}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Uppercased Text",{"Index", "international_plan", "voice_mail_plan"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "plan_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

