table dim_area_code
	lineageTag: da8a4450-7900-415b-8650-73b31964e0e2

	column area_code_key
		dataType: int64
		formatString: 0
		lineageTag: 898f331a-88e9-4c73-b7a4-680a2f4ad806
		summarizeBy: none
		sourceColumn: area_code_key

		annotation SummarizationSetBy = Automatic

	column area_code
		dataType: int64
		formatString: 0
		lineageTag: f5ecd134-f205-4fa9-9a56-54665bb008a9
		summarizeBy: none
		sourceColumn: area_code

		annotation SummarizationSetBy = Automatic

	partition dim_area_code = m
		mode: import
		queryGroup: teleco_churn_model
		source =
				let
				    Source = complete_data,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"state", "account_length", "international_plan", "voice_mail_plan", "number_vmail_messages", "total_day_minutes", "total_day_calls", "total_day_charge", "total_eve_minutes", "total_eve_calls", "total_eve_charge", "total_night_minutes", "total_night_calls", "total_night_charge", "total_intl_minutes", "total_intl_calls", "total_intl_charge", "customer_service_calls", "churn", "customer_key"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "area_code"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "area_code_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

